### PR TITLE
ENHANCEMENT: SilverStripe 4.x compatibility

### PR DESCRIPTION
**Pull request by robbieaverill**
## Summary

* Implement PSR-4 autoloading and namespaces
* Update composer constraint for SilverStripe 4.x compat and add ^2.0 dev alias
* Adjust minor changes in framework ORM
* Update readme to include namespaced examples
* Convert to PSR-2 style guidelines, add editorconfig file

## Requirements

- [ ] Create branch from current `master` for maintenance of current version, e.g. `1` before merging

### CODE REVIEW

**Comment by robbieaverill** [comment]
It's a shame that the file tracking was lost, I guess the namespacing combined with the PSR-2 style changes made it forget who it was :(

**Comment by UndefinedOffset** [comment]
Thanks for this, I'll review next week and see about merging it. I wonder if the reason the file tracking was lost is because the commit is squashed? I wonder if it was broken into more than one commit if it would fix it. For example convert to psr-2 and such commit then move the files commit. (Not sure though)

**Comment by robbieaverill** [comment]
Hey @UndefinedOffset 

Yea potentially. I had originally put them into separate commits but had squashed them.

I'm happy to reset them and re-do the upgrade changes. It's probably worthwhile to ensure that the history is retained.

**Comment by UndefinedOffset** [comment]
Ya I think it will be worth while keeping the history if possible

**Comment by robbieaverill** [comment]
Agreed - let me re re re

**Comment by robbieaverill** [comment]
@UndefinedOffset I've re-applied the changes across two separate commits - the first renamed the class paths and the second implements the required upgrade changes.

The overall diff in Git CLI and GitHub is still showing that the files are deleted and created, but the individual commits show correctly.

I'll try a dryrun merging of this locally and see what happens.

**Comment by robbieaverill** [comment]
I think I'm changing too much of the classes at once, git thinks they're new files.

I'll separate the second commit into a bunch of different commits doing smaller changes each to help. Will push when it's ready.

**Comment by robbieaverill** [comment]
OK, that hasn't fixed it either. I'll close this and submit each commit as a separate pull request.

They'll possibly need to be rebased, and will definitely need to be merged in order.

Sorry about this!

**Pull request closed without merging**
