### PR TITLE
UPDATE re-implement cache

### LINKED ISSUE #20: Re-implement cache code in DBMarkdown
Due to cache changes in framework, this was commented out for an initial release of 4 compatibility.

https://github.com/UndefinedOffset/silverstripe-markdown/blob/master/src/Model/FieldTypes/DBMarkdown.php#L75-L77

### PR DESCRIPTION
**Pull request by muskie9**
NEW DBMarkdownTest for partial coverage
NEW travis, scrutinizer and test configuration files

resolves #20

### CODE REVIEW

**Comment by muskie9** [comment]
I don't quite have travis working correctly. I'll need to circle back to this and track down the cause. The setup is essentially the same we've implemented on other open source modules so the failures are a little odd.

**Comment by UndefinedOffset** [comment]
I'll merge, and you or I can look into the test failures

**Comment by muskie9** [comment]
for reference: https://travis-ci.org/muskie9/silverstripe-markdown

**Comment by UndefinedOffset** [comment]
It looks like phpunit isn't even being installed by composer that could be the issue, it may need to be added as a require dev dependency.

**Comment by muskie9** [comment]
Major 🤦‍♂ on that one. Turns out the bootstrap file I was referencing was incorrect as well. Fixed it up so now the tests should pass on travis.

**Comment by UndefinedOffset** [comment]
Looks like they did :) i'll get this merged

**Pull request merged**
